<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ram-laptop" name="com.selenium.test.TestNGDataDrivenTest" tests="1" failures="0" timestamp="24 Dec 2010 16:57:09 GMT" time="0.000" errors="1">
  <testcase name="wikiTest" time="0.000" classname="com.selenium.test.TestNGDataDrivenTest">
    <error type="org.testng.TestNGException" message="
Data Provider public java.lang.String[] com.selenium.test.TestNGDataDrivenTest.dataProvider() must return either Object[][] or Iterator&lt;Object&gt;[], not class [Ljava.lang.String;">
      <![CDATA[org.testng.TestNGException: 
Data Provider public java.lang.String[] com.selenium.test.TestNGDataDrivenTest.dataProvider() must return either Object[][] or Iterator<Object>[], not class [Ljava.lang.String;
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:132)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:391)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1313)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1022)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1122)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1125)
	at org.testng.TestRunner.privateRun(TestRunner.java:749)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:317)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:312)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:274)
	at org.testng.SuiteRunner.run(SuiteRunner.java:223)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:954)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:883)
	at org.testng.TestNG.run(TestNG.java:817)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:110)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:174)
]]>
    </error>
  </testcase>
</testsuite>
